CREATE TABLE `companies` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_type` text NOT NULL,
	`company_name` text NOT NULL,
	`currency` text NOT NULL,
	`gst_applicable` text NOT NULL,
	`gstin` text,
	`state_code` text,
	`country` text NOT NULL,
	`address_line_1` text NOT NULL,
	`address_line_2` text,
	`state` text NOT NULL,
	`city` text NOT NULL,
	`email` text NOT NULL,
	`contact_no` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `customers` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`customer_type` text NOT NULL,
	`salutation` text,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`pan_number` text,
	`company_name` text NOT NULL,
	`currency` text NOT NULL,
	`gst_applicable` text NOT NULL,
	`gstin` text,
	`state_code` text,
	`billing_country` text NOT NULL,
	`billing_state` text NOT NULL,
	`billing_city` text NOT NULL,
	`billing_address_line_1` text NOT NULL,
	`billing_address_line_2` text,
	`shipping_country` text NOT NULL,
	`shipping_state` text NOT NULL,
	`shipping_city` text NOT NULL,
	`shipping_address_line_1` text NOT NULL,
	`shipping_address_line_2` text,
	`contact_no` text NOT NULL,
	`alternate_contact_no` text,
	`email` text NOT NULL
);
